#!/bin/sh

. "${PM_FUNCTIONS}"

case "$1" in
  hibernate|suspend)
    if [ -d /sys/devices/virtual/misc/rfkill -a -x /usr/sbin/rfkill -a -x /etc/rc.d/rc.bluetooth ]; then
      rfkill block bluetooth
    fi
   ;;
  thaw|resume)
    if [ -d /sys/devices/virtual/misc/rfkill -a -x /usr/sbin/rfkill -a -x /etc/rc.d/rc.bluetooth ]; then
      rfkill unblock bluetooth
    fi
    ;;
  *)
    ;;
esac

