#!/bin/sh

# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2015, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=nmap
VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
BUILD=${BUILD:-1}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i586 ;;
    arm*) export ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

NUMJOBS=${NUMJOBS:-" -j7 "}

TMP=${TMP:-/tmp}
PKG=$TMP/package-nmap

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf nmap-$VERSION
tar xvf $CWD/nmap-$VERSION.tar.?z* || exit 1
cd nmap-$VERSION || exit 1

chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

sed -i "s,share/man/man1,man/man1,g" ndiff/setup.py

# --without-nmap-update is needed below to avoid depending on apr and subversion libraries.
# It's not worth the feature IMHO.
LIBS="-lnl" \
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --with-liblua=included \
  --with-libpcap=included \
  --mandir=/usr/man \
  --docdir=/usr/doc/nmap-$VERSION \
  --without-nmap-update \
  --build=$ARCH-slackware-linux || exit 1

make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/usr/doc/nmap-$VERSION
cp -a COPYING* HACKING INSTALL \
  docs/licenses/ \
  docs/*.txt \
  $PKG/usr/doc/nmap-$VERSION
( cd docs
  # It looks like all of these translations are gone from the 4.00+ tarball, and
  # most of them are not available on the web site.  Sorry -- I didn't do it.
  if [ -f nmap_german.1 ] ; then
    mkdir -p $PKG/usr/man/de/man1
    cat nmap_german.1 | gzip -9c > $PKG/usr/man/de/man1/nmap.1.gz
  fi
  if [ -f nmap_spanish.1 ] ; then
    mkdir -p $PKG/usr/man/es/man1
    cat nmap_spanish.1 | gzip -9c > $PKG/usr/man/es/man1/nmap.1.gz
  fi
  if [ -f nmap_french.1 ] ; then
    mkdir -p $PKG/usr/man/fr/man1
    cat nmap_french.1 | gzip -9c > $PKG/usr/man/fr/man1/nmap.1.gz
  fi
  if [ -f nmap_italian.1 ] ; then
    mkdir -p $PKG/usr/man/it/man1
    cat nmap_italian.1 | gzip -9c > $PKG/usr/man/it/man1/nmap.1.gz
  fi
  if [ -f nmap_lithuanian.1 ] ; then
    mkdir -p $PKG/usr/man/lt/man1
    cat nmap_lithuanian.1 | gzip -9c > $PKG/usr/man/lt/man1/nmap.1.gz
  fi
  if [ -f nmap_portuguese.1 ] ; then
    mkdir -p $PKG/usr/man/pt/man1
    cat nmap_portuguese.1 | gzip -9c > $PKG/usr/man/pt/man1/nmap.1.gz
  fi
  if [ -f nmap_russian.1 ] ; then
    mkdir -p $PKG/usr/man/ru/man1
    cat nmap_russian.1 | gzip -9c > $PKG/usr/man/ru/man1/nmap.1.gz
  fi
)

# If there's a ChangeLog, installing at least part of the recent history
# is useful, but don't let it get totally out of control:
if [ -r CHANGELOG ]; then
  DOCSDIR=$(echo $PKG/usr/doc/*-$VERSION)
  cat CHANGELOG | head -n 1000 > $DOCSDIR/CHANGELOG
  touch -r CHANGELOG $DOCSDIR/CHANGELOG
fi

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# Compress and link manpages, if any:
if [ -d $PKG/usr/man ]; then
  ( cd $PKG/usr/man
    for manpagedir in $(find . -type d -name "man*") ; do
      ( cd $manpagedir
        for eachpage in $( find . -type l -maxdepth 1) ; do
          ln -s $( readlink $eachpage ).gz $eachpage.gz
          rm $eachpage
        done
        gzip -9 *.?
      )
    done
  )
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $TMP/nmap-$VERSION-$ARCH-$BUILD.txz

