#!/bin/sh

# Copyright 2008, 2009, 2011, 2012, 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=t1lib
VERSION=${VERSION:-$(echo $PKGNAM-*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
BUILD=${BUILD:-3}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i586 ;;
    arm*) export ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

NUMJOBS=${NUMJOBS:-" -j7 "}

TMP=${TMP:-/tmp}
PKG=$TMP/package-t1lib
rm -rf $PKG
mkdir -p $TMP $PKG/usr

cd $TMP
rm -rf t1lib-$VERSION
tar xvf $CWD/t1lib-$VERSION.tar.?z* || exit 1
cd t1lib-$VERSION

# Apply Debian's patch since upstream seems inactive:
zcat $CWD/t1lib_5.1.2-3.5.diff.gz | patch -p1 --verbose || exit 1

# I don't think anyone is applying this first one:
#cat debian/patches/segfault.diff -b -z .segf | patch -p1 --verbose || exit 1
# UUOCFTW:
cat debian/patches/no-config.diff | patch -p1 --verbose || exit 1
cat debian/patches/no-docs.diff | patch -p1 --verbose || exit 1
cat debian/patches/lib-cleanup.diff | patch -p1 --verbose || exit 1
cat debian/patches/format-security.diff | patch -p1 --verbose || exit 1
cat debian/patches/CVE-2011-0764.diff | patch -p1 --verbose || exit 1
cat debian/patches/CVE-2011-1552_1553_1554.patch | patch -p1 --verbose || exit 1
cat debian/patches/CVE-2010-2642.patch | patch -p1 --verbose || exit 1

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --enable-static=no \
  --build=$ARCH-slackware-linux

make $NUMJOBS || make || exit 1
make install prefix=$PKG/usr libdir=$PKG/usr/lib${LIBDIRSUFFIX} || exit 1

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

chmod 755 $PKG/usr/lib${LIBDIRSUFFIX}/*.so

mkdir -p $PKG/usr/doc/t1lib-$VERSION
cp -a \
  Change* COPYING* *GPL* LICENSE* README* \
  $PKG/usr/doc/t1lib-$VERSION

mkdir -p $PKG/usr/share/t1lib
cp -a Fonts $PKG/usr/share/t1lib
/bin/ls $PKG/usr/share/t1lib/Fonts/afm/*.afm /usr/share/fonts/Type1/*.afm | sort | uniq | wc -l | sed -e 's/ //g' > $PKG/usr/share/t1lib/FontDataBase
( cd $PKG/usr/share/t1lib/Fonts/afm ; /bin/ls *.afm ; cd /usr/share/fonts/Type1 ; /bin/ls *.afm ) | sort | uniq >> $PKG/usr/share/t1lib/FontDataBase
cat << EOF > $PKG/usr/share/t1lib/t1lib.config
This is a configuration file for t1lib

FONTDATABASE=/usr/share/t1lib/FontDataBase
ENCODING=/usr/share/t1lib/Fonts/enc
AFM=/usr/share/t1lib/Fonts/afm:/usr/share/fonts/Type1
TYPE1=/usr/share/t1lib/Fonts/type1:/usr/share/fonts/Type1
EOF

mkdir -p $PKG/etc/profile.d
cat << EOF > $PKG/etc/profile.d/t1lib.sh
T1LIB_CONFIG=/usr/share/t1lib/t1lib.config
export T1LIB_CONFIG
EOF
cat << EOF > $PKG/etc/profile.d/t1lib.csh
setenv T1LIB_CONFIG /usr/share/t1lib/t1lib.config
EOF
chmod 755 $PKG/etc/profile.d/*

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $TMP/t1lib-$VERSION-$ARCH-$BUILD.txz

